import DS from 'ember-data';

const templates = [
    [ "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white" ],
    [ "green", "pink", "pink", "pink", "pink", "pink", "pink", "pink", "pink", "green", "green", "purple", "purple", "purple", "black", "red", "red", "grey", "yellow", "green", "green", "white", "black", "purple", "white", "pink", "white", "yellow", "yellow", "green", "green", "red", "white", "purple", "purple", "black", "yellow", "yellow", "grey", "green", "green", "red", "grey", "black", "yellow", "yellow", "black", "grey", "red", "green", "green", "white", "grey", "yellow", "yellow", "purple", "purple", "grey", "red", "green", "green", "black", "grey", "yellow", "black", "black", "purple", "white", "pink", "green", "green", "green", "yellow", "yellow", "white", "pink", "white", "purple", "purple", "green", "pink", "green", "yellow", "grey", "red", "red", "black", "green", "green", "green", "indigo", "green", "green", "green", "green", "green", "green", "green", "pink", "indigo" ],
    [ "purple", "white", "blue", "white", "red", "white", "pink", "blue", "yellow", "yellow", "purple", "purple", "blue", "red", "red", "pink", "white", "blue", "blue", "yellow", "pink", "pink", "red", "red", "pink", "yellow", "yellow", "blue", "yellow", "yellow", "pink", "white", "red", "blue", "yellow", "yellow", "yellow", "blue", "yellow", "black", "pink", "pink", "red", "pink", "pink", "teal", "teal", "teal", "teal", "white", "yellow", "yellow", "red", "white", "black", "black", "black", "black", "teal", "teal", "yellow", "white", "black", "black", "blue", "blue", "purple", "pink", "pink", "teal", "black", "black", "yellow", "yellow", "blue", "blue", "pink", "pink", "white", "teal", "white", "yellow", "yellow", "blue", "blue", "pink", "pink", "purple", "purple", "white", "yellow", "white", "blue", "blue", "pink", "pink", "blue", "white", "purple", "purple" ],
    [ "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "green", "green", "blue", "purple", "purple", "purple", "purple", "purple", "purple", "blue", "green", "green", "blue", "purple", "orange", "orange", "orange", "orange", "purple", "blue", "green", "green", "blue", "purple", "pink", "pink", "pink", "pink", "purple", "blue", "green", "green", "blue", "purple", "yellow", "yellow", "yellow", "yellow", "purple", "blue", "green", "green", "blue", "purple", "black", "black", "black", "black", "purple", "blue", "green", "green", "blue", "purple", "purple", "purple", "purple", "purple", "purple", "blue", "green", "green", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green" ],
    [ "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red", "yellow", "red" ],
    [ "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "white", "white", "blue", "blue", "blue", "blue", "white", "blue", "blue", "blue", "blue", "white", "white", "blue", "blue", "blue", "white", "white", "blue", "blue", "black", "blue", "blue", "blue", "black", "blue", "blue", "blue", "blue", "blue", "black", "black", "black", "black", "black", "blue", "blue", "blue", "blue", "blue", "black", "yellow", "black", "yellow", "black", "blue", "blue", "blue", "blue", "blue", "black", "black", "black", "black", "black", "black", "black", "black", "blue", "green", "green", "black", "pink", "black", "black", "black", "black", "black", "green", "green", "green", "black", "black", "black", "black", "black", "black", "black", "green", "green", "green", "black", "green", "black", "green", "black", "green", "black", "black" ]  
]
export default DS.Model.extend({
    templatePicture: DS.belongsTo('picture',{ async: false }),
    gamePicture: DS.belongsTo('picture',{ async: false }),
    init(){
        this._super(...arguments);
        this.set('templatePicture',this.store.createRecord('picture'));
        this.set('gamePicture',this.store.createRecord('picture'));
        this.pickRandomTemplate();
    },
    pickRandomTemplate(){
        let picked = templates[Math.floor(Math.random() * templates.length)];
        this.templatePicture.load(picked);
        this.gamePicture.clear();
    }

});
